name: Publish to PyPi

on: 
  push:
      branches:
        - main
      tags:
        - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build 
      
      - name: Build Project
        run: python3 -m build --sdist --wheel --outdir dist/
        
      - name: Publish a Python distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
